name: Automatic Testing for Resource Management Web App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code from GitHub Repo
      uses: actions/checkout@v3
      
    - name: Setup Node.js in Ubuntu
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Clean install dependencies
      run: npm ci
      
    - name: Setup test environment
      run: |
        mkdir -p utils
        echo '[]' > utils/book.json
        chmod 666 utils/book.json
        
    - name: Run tests
      run: |
        DEBUG=* npm run backend-test
      env:
        CI: true
        NODE_ENV: test
