name: Automatic Testing for book Web App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code from GitHub Repo
      uses: actions/checkout@v3
      
    - name: Setup Node.js in Ubuntu
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Clean install dependencies
      run: npm ci
      
    - name: Run tests
      run: |
        npm run backend-test
      env:
        CI: true
